version: "3"

volumes:
  data:

services:
  apis:
    build:
      context: ./APIs
      dockerfile: Dockerfile
    volumes:
      - ./APIs/src:/app/src
    ports:
      - "8000:8000"
  frontend:
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile
    volumes:
      - ./example-frontend/src:/app/src
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql