version: "3"

volumes:
  data: 

services:
  apis:
    build:
      context: ./APIs
      dockerfile: Dockerfile
    volumes:
      - ./APIs/src:/app/src
    ports:
      - "8000:8000"
  frontend:
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile
    volumes:
      - ./example-frontend/src:/app/src
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      # Comment "- data:/var/lib/postgresql" and uncomment below to save the database in the current directory
      - ./data:/var/lib/postgresql/data
      # - data:/var/lib/postgresql

      # Runs *.sh or *.sql when first creating the database, if the database already exists, the files do not execute
      # read more [here](https://levelup.gitconnected.com/creating-and-filling-a-postgres-db-with-docker-compose-e1607f6f882f)
      - ./database-set-up.sh:/docker-entrypoint-initdb.d/database-set-up.sh # the shell script is required to create the tables within the correct database
      # mounts the sql files to be used within the start up shell script
      - ./sql:/sql